### ISSUE TITLE
Fixing Timed Messages when setting it for longer duration

### ISSUE THREAD

**Issue by Hu1k1e** [svijaymohan745/Discord.JS-12-CON-Bot#7]
Timed interval messages work for short duration. But doesn't trigger when setting it for, like a week.

**Comment by nevinbaiju** [comment]
Fixed in [b95442c](https://github.com/svijaymohan745/Discord.JS-12-CON-Bot/commit/827f0a10feb8a3c932a002ec815fc14b9722ca7c)
